Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../network-node01/organizations/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        OrdererEndpoints:
            - 10.137.3.70:7050
    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org1.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org1MSP.peer')"
        AnchorPeers:
            - Host: &Node01Addr 10.137.3.70
              Port: 7051
    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org2.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org2MSP.peer')"
        AnchorPeers:
            - Host: *Node01Addr
              Port: 9051
    - &Org3
        Name: Org3MSP
        ID: Org3MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org3.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org3MSP.admin', 'Org3MSP.peer', 'Org3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org3MSP.admin', 'Org3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org3MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org3MSP.peer')"
        AnchorPeers:
            - Host: &Node02Addr 10.137.3.71
              Port: 10051
    - &Org4
        Name: Org4MSP
        ID: Org4MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org4.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org4MSP.admin', 'Org4MSP.peer', 'Org4MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org4MSP.admin', 'Org4MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org4MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org4MSP.peer')"
        AnchorPeers:
            - Host: *Node02Addr
              Port: 11051
    - &Org5
        Name: Org5MSP
        ID: Org5MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org5.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org5MSP.admin', 'Org5MSP.peer', 'Org5MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org5MSP.admin', 'Org5MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org5MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org5MSP.peer')"
        AnchorPeers:
            - Host: &Node03Addr 10.137.3.68
              Port: 12051
    - &Org6
        Name: Org6MSP
        ID: Org6MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org6.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org6MSP.admin', 'Org6MSP.peer', 'Org6MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org6MSP.admin', 'Org6MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org6MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org6MSP.peer')"
        AnchorPeers:
            - Host: *Node03Addr
              Port: 13051
    - &Org7
        Name: Org7MSP
        ID: Org7MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org7.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org7MSP.admin', 'Org7MSP.peer', 'Org7MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org7MSP.admin', 'Org7MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org7MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org7MSP.peer')"
        AnchorPeers:
            - Host: &Node04Addr 10.137.3.20
              Port: 14051
    - &Org8
        Name: Org8MSP
        ID: Org8MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org8.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org8MSP.admin', 'Org8MSP.peer', 'Org8MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org8MSP.admin', 'Org8MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org8MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org8MSP.peer')"
        AnchorPeers:
            - Host: *Node04Addr
              Port: 15051
    - &Org9
        Name: Org9MSP
        ID: Org9MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org9.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org9MSP.admin', 'Org9MSP.peer', 'Org9MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org9MSP.admin', 'Org9MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org9MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org9MSP.peer')"
        AnchorPeers:
            - Host: &Node05Addr 10.137.3.69
              Port: 16051
    - &Org10
        Name: Org10MSP
        ID: Org10MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org10.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org10MSP.admin', 'Org10MSP.peer', 'Org10MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org10MSP.admin', 'Org10MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org10MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org10MSP.peer')"
        AnchorPeers:
            - Host: *Node05Addr
              Port: 17051
    - &Org11
        Name: Org11MSP
        ID: Org11MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org11.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org11MSP.admin', 'Org11MSP.peer', 'Org11MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org11MSP.admin', 'Org11MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org11MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org11MSP.peer')"
        AnchorPeers:
            - Host: 10.137.3.6
              Port: 7051
    - &Org12
        Name: Org12MSP
        ID: Org12MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org12.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org12MSP.admin', 'Org12MSP.peer', 'Org12MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org12MSP.admin', 'Org12MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org12MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org12MSP.peer')"
        AnchorPeers:
            - Host: 10.137.3.23
              Port: 9051
    - &Org13
        Name: Org13MSP
        ID: Org13MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org13.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org13MSP.admin', 'Org13MSP.peer', 'Org13MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org13MSP.admin', 'Org13MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org13MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org13MSP.peer')"
        AnchorPeers:
            - Host: 10.137.3.90
              Port: 10051
    - &Org14
        Name: Org14MSP
        ID: Org14MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org14.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org14MSP.admin', 'Org14MSP.peer', 'Org14MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org14MSP.admin', 'Org14MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org14MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org14MSP.peer')"
        AnchorPeers:
            - Host: 10.137.3.91
              Port: 11051
    - &Org15
        Name: Org15MSP
        ID: Org15MSP
        MSPDir: ../network-node01/organizations/peerOrganizations/org15.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org15MSP.admin', 'Org15MSP.peer', 'Org15MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org15MSP.admin', 'Org15MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org15MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Org15MSP.peer')"
        AnchorPeers:
            - Host: 10.137.3.88
              Port: 12051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft

    EtcdRaft:
        Consenters:
        - Host: orderer.example.com
          Port: 7050
          ClientTLSCert: ../network-node01/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
          ServerTLSCert: ../network-node01/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
                    - *Org4
                    - *Org5
                    - *Org6
                    - *Org7
                    - *Org8
                    - *Org9
                    - *Org10
                    - *Org11
                    - *Org12
                    - *Org13
                    - *Org14
                    - *Org15
    TwoOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
                - *Org4
                - *Org5
                - *Org6
                - *Org7
                - *Org8
                - *Org9
                - *Org10
                - *Org11
                - *Org12
                - *Org13
                - *Org14
                - *Org15
            Capabilities:
                <<: *ApplicationCapabilities

