version: '2'

volumes:
  peer0.org61.example.com:
  peer0.org62.example.com:
  peer0.org63.example.com:
  peer0.org64.example.com:
  peer0.org65.example.com:
  peer0.org66.example.com:
  peer0.org67.example.com:
  peer0.org68.example.com:
  peer0.org69.example.com:
  peer0.org70.example.com:

networks:
  test:

services:

  peer0.org61.example.com:
    container_name: peer0.org61.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org61.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org61.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:7051
      - CORE_PEER_LOCALMSPID=Org61MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org61.example.com/peers/peer0.org61.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org61.example.com/peers/peer0.org61.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org61.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - test

  peer0.org62.example.com:
    container_name: peer0.org62.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org62.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org62.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:9051
      - CORE_PEER_LOCALMSPID=Org62MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org62.example.com/peers/peer0.org62.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org62.example.com/peers/peer0.org62.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org62.example.com:/var/hyperledger/production
    ports:
      - 9051:9051
    networks:
      - test

  peer0.org63.example.com:
    container_name: peer0.org63.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org63.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org63.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:10051
      - CORE_PEER_LOCALMSPID=Org63MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org63.example.com/peers/peer0.org63.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org63.example.com/peers/peer0.org63.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org63.example.com:/var/hyperledger/production
    ports:
      - 10051:10051
    networks:
      - test

  peer0.org64.example.com:
    container_name: peer0.org64.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org64.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org64.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:11051
      - CORE_PEER_LOCALMSPID=Org64MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org64.example.com/peers/peer0.org64.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org64.example.com/peers/peer0.org64.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org64.example.com:/var/hyperledger/production
    ports:
      - 11051:11051
    networks:
      - test

  peer0.org65.example.com:
    container_name: peer0.org65.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org65.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org65.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:12051
      - CORE_PEER_LOCALMSPID=Org65MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org65.example.com/peers/peer0.org65.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org65.example.com/peers/peer0.org65.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org65.example.com:/var/hyperledger/production
    ports:
      - 12051:12051
    networks:
      - test

  peer0.org66.example.com:
    container_name: peer0.org66.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org66.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org66.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:13051
      - CORE_PEER_LOCALMSPID=Org66MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org66.example.com/peers/peer0.org66.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org66.example.com/peers/peer0.org66.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org66.example.com:/var/hyperledger/production
    ports:
      - 13051:13051
    networks:
      - test

  peer0.org67.example.com:
    container_name: peer0.org67.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org67.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org67.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:14051
      - CORE_PEER_LOCALMSPID=Org67MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org67.example.com/peers/peer0.org67.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org67.example.com/peers/peer0.org67.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org67.example.com:/var/hyperledger/production
    ports:
      - 14051:14051
    networks:
      - test

  peer0.org68.example.com:
    container_name: peer0.org68.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org68.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org68.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:15051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:15051
      - CORE_PEER_LOCALMSPID=Org68MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org68.example.com/peers/peer0.org68.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org68.example.com/peers/peer0.org68.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org68.example.com:/var/hyperledger/production
    ports:
      - 15051:15051
    networks:
      - test

  peer0.org69.example.com:
    container_name: peer0.org69.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org69.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:16051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:16051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org69.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:16051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:16051
      - CORE_PEER_LOCALMSPID=Org69MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org69.example.com/peers/peer0.org69.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org69.example.com/peers/peer0.org69.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org69.example.com:/var/hyperledger/production
    ports:
      - 16051:16051
    networks:
      - test

  peer0.org70.example.com:
    container_name: peer0.org70.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org70.example.com
      - CORE_PEER_ADDRESS=10.137.3.23:17051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:17051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org70.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.23:17051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.23:17051
      - CORE_PEER_LOCALMSPID=Org70MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org70.example.com/peers/peer0.org70.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org70.example.com/peers/peer0.org70.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org70.example.com:/var/hyperledger/production
    ports:
      - 17051:17051
    networks:
      - test


