OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - &Node01Addr 10.137.3.70
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node01Addr
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node01Addr
    Users:
      Count: 1
  - Name: Org4
    Domain: org4.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node01Addr
    Users:
      Count: 1
  - Name: Org5
    Domain: org5.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node01Addr
    Users:
      Count: 1
  - Name: Org6
    Domain: org6.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node01Addr
    Users:
      Count: 1
  - Name: Org7
    Domain: org7.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node01Addr
    Users:
      Count: 1
  - Name: Org8
    Domain: org8.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node01Addr
    Users:
      Count: 1
  - Name: Org9
    Domain: org9.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node01Addr
    Users:
      Count: 1
  - Name: Org10
    Domain: org10.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node01Addr
    Users:
      Count: 1
  - Name: Org11
    Domain: org11.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - &Node02Addr 10.137.3.71
    Users:
      Count: 1
  - Name: Org12
    Domain: org12.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node02Addr
    Users:
      Count: 1
  - Name: Org13
    Domain: org13.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node02Addr
    Users:
      Count: 1
  - Name: Org14
    Domain: org14.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node02Addr
    Users:
      Count: 1
  - Name: Org15
    Domain: org15.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node02Addr
    Users:
      Count: 1
  - Name: Org16
    Domain: org16.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node02Addr
    Users:
      Count: 1
  - Name: Org17
    Domain: org17.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node02Addr
    Users:
      Count: 1
  - Name: Org18
    Domain: org18.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node02Addr
    Users:
      Count: 1
  - Name: Org19
    Domain: org19.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node02Addr
    Users:
      Count: 1
  - Name: Org20
    Domain: org20.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - *Node02Addr
    Users:
      Count: 1

