version: '2'

volumes:
  peer0.org41.example.com:
  peer0.org42.example.com:
  peer0.org43.example.com:
  peer0.org44.example.com:
  peer0.org45.example.com:
  peer0.org46.example.com:
  peer0.org47.example.com:
  peer0.org48.example.com:
  peer0.org49.example.com:
  peer0.org50.example.com:

networks:
  test:

services:

  peer0.org41.example.com:
    container_name: peer0.org41.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org41.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org41.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:7051
      - CORE_PEER_LOCALMSPID=Org41MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org41.example.com/peers/peer0.org41.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org41.example.com/peers/peer0.org41.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org41.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - test

  peer0.org42.example.com:
    container_name: peer0.org42.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org42.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org42.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:9051
      - CORE_PEER_LOCALMSPID=Org42MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org42.example.com/peers/peer0.org42.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org42.example.com/peers/peer0.org42.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org42.example.com:/var/hyperledger/production
    ports:
      - 9051:9051
    networks:
      - test

  peer0.org43.example.com:
    container_name: peer0.org43.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org43.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org43.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:10051
      - CORE_PEER_LOCALMSPID=Org43MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org43.example.com/peers/peer0.org43.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org43.example.com/peers/peer0.org43.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org43.example.com:/var/hyperledger/production
    ports:
      - 10051:10051
    networks:
      - test

  peer0.org44.example.com:
    container_name: peer0.org44.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org44.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org44.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:11051
      - CORE_PEER_LOCALMSPID=Org44MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org44.example.com/peers/peer0.org44.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org44.example.com/peers/peer0.org44.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org44.example.com:/var/hyperledger/production
    ports:
      - 11051:11051
    networks:
      - test

  peer0.org45.example.com:
    container_name: peer0.org45.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org45.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org45.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:12051
      - CORE_PEER_LOCALMSPID=Org45MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org45.example.com/peers/peer0.org45.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org45.example.com/peers/peer0.org45.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org45.example.com:/var/hyperledger/production
    ports:
      - 12051:12051
    networks:
      - test

  peer0.org46.example.com:
    container_name: peer0.org46.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org46.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org46.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:13051
      - CORE_PEER_LOCALMSPID=Org46MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org46.example.com/peers/peer0.org46.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org46.example.com/peers/peer0.org46.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org46.example.com:/var/hyperledger/production
    ports:
      - 13051:13051
    networks:
      - test

  peer0.org47.example.com:
    container_name: peer0.org47.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org47.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org47.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:14051
      - CORE_PEER_LOCALMSPID=Org47MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org47.example.com/peers/peer0.org47.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org47.example.com/peers/peer0.org47.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org47.example.com:/var/hyperledger/production
    ports:
      - 14051:14051
    networks:
      - test

  peer0.org48.example.com:
    container_name: peer0.org48.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org48.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org48.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:15051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:15051
      - CORE_PEER_LOCALMSPID=Org48MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org48.example.com/peers/peer0.org48.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org48.example.com/peers/peer0.org48.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org48.example.com:/var/hyperledger/production
    ports:
      - 15051:15051
    networks:
      - test

  peer0.org49.example.com:
    container_name: peer0.org49.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org49.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:16051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:16051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org49.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:16051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:16051
      - CORE_PEER_LOCALMSPID=Org49MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org49.example.com/peers/peer0.org49.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org49.example.com/peers/peer0.org49.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org49.example.com:/var/hyperledger/production
    ports:
      - 16051:16051
    networks:
      - test

  peer0.org50.example.com:
    container_name: peer0.org50.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org50.example.com
      - CORE_PEER_ADDRESS=10.137.3.69:17051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:17051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org50.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=10.137.3.69:17051
      - CORE_PEER_GOSSIP_BOOTSTRAP=10.137.3.69:17051
      - CORE_PEER_LOCALMSPID=Org50MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org50.example.com/peers/peer0.org50.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org50.example.com/peers/peer0.org50.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org50.example.com:/var/hyperledger/production
    ports:
      - 17051:17051
    networks:
      - test


